### ISSUE TITLE
IOS Support

### ISSUE THREAD

**Issue by ankibalyan** [nandarustam/fcm-push#12]
How to integrate  to send notifications to ios devices? Does registration token will work for both IOS/Android in the same way?

**Comment by nandarustam** [comment]
Yes it does!

**Comment by jlcvp** [comment]
you should be warned that you need to set the priority field to high and the content_available to true to get instant notification in iOS devices

**Comment by ankibalyan** [comment]
VOIP Pushkit? 
What I've implemented with apn is VoIP notification, so that as soon as a notification arrives it opens the app in the background and update the notification delivery report to the server / other clients.

**Comment by ngKisor** [comment]
Push is working fine when app is open in IOS but it doesnot work while app is closed how to solve this. i have already set content_available to true and priority to high but issue remain same.

**Comment by ankibalyan** [comment]
@ngKisor when you set `content_available` to true, this is a silent notification. It will wake your app in background for few seconds (let say 30 seconds) and after it closes.
when you are sending a silent push, you should not send the `alert` message otherwise it will act as normal notification.

PS: you should not send a large number of silent push in certain time, apn will block your further silent push notification.
